Simulation = "CentrilizedAuction"
Servers = 1
Hosts = 1
Depth = 1
Rounds = 2
RunWait = "6000s"
Suite = "Ed25519"
BlockInterval = "1s"

# This section of the file lists test scenarios, one per line, with variables
# to vary, separated by tabs.
Bidders,    Bids
10,     4
50,     4
#100,     4
#200,     4
#400,     4
#800,     4
#1600,     4
#3200,     4
#5000,     4
#10000,     4